### ISSUE TITLE
dif number

### ISSUE THREAD

**Issue by ZhengguoTan** [CongyuLiao/BUDA_SLORAKS#1]
Dear Congyu,

Thank you for sharing such excellent open-source codes!

It seems like it might be good to change the number "18" in this line:

https://github.com/CongyuLiao/BUDA_SLORAKS/blob/main/BUDA_SLORAKS/codes/RUN_BUDA_S_LORAKS.m#L22

to "1", in accordance with the shared data.

Thank you again for your codes!

Best Regards,
Zhengguo

**Comment by CongyuLiao** [comment]
Thanks, I have changed the "dif" to 1.

**Comment by CongyuLiao** [comment]
Thanks, I have changed the "dif" to 1.
